import { type AxiosResponse } from "axios";
import type { LinkIssueSeverity, LinkZone, Location, PageData, ReportData } from "@arachnodex/core";
import { BaseJob, OutputHelper, type ArachnodexRuntime, type JobCommandParser, type Profiler } from "@arachnodex/core";
export { default as CommandParser } from "./cmd.js";
type LinkIssue = {
    severity: LinkIssueSeverity;
    group: string;
    code: string;
    message: string;
    targetUrl?: string;
    sourceUrl?: string;
    rawHref?: string;
    htmlSnippet?: string;
    normalizedUrl?: string;
    pageUrl?: string;
    linkedUrl?: string;
    canonicalUrl?: string;
    expectedCanonicalUrl?: string;
    canonicalHrefs?: string[];
    decodedPath?: string;
    networkErrorCode?: string;
    networkErrorMessage?: string;
    statusCode?: number;
    finalUrl?: string;
    redirectChain?: string[];
    zone?: LinkZone;
    assetKind?: string;
    sourceLabel?: string;
    occurrenceDetails?: LinkOccurrence[];
};
type AssetKind = 'script' | 'stylesheet' | 'image' | 'srcset' | 'icon' | 'manifest' | 'preload' | 'media' | 'track' | 'poster' | 'iframe' | 'embed' | 'object' | 'meta' | 'svg' | 'inline-style' | 'css-url' | 'css-import' | 'css-source-map' | 'js-url' | 'js-source-map';
type AssetRecord = {
    targetUrl: string;
    rawUrl: string;
    sourceUrl: string;
    sourceLabel: string;
    kind: AssetKind;
    htmlSnippet?: string;
    zone: LinkZone;
    isExternal: boolean;
    occurrences: LinkOccurrence[];
};
type IgnoredIssuePattern = {
    pattern: RegExp;
    codes: Set<string> | null;
    groups: Set<string> | null;
    severities: Set<LinkIssueSeverity> | null;
};
type LinkOccurrence = {
    referer: string;
    zone: LinkZone;
};
type LinkOccurrenceSummary = {
    targetUrl: string;
    occurrenceCount: number;
    pageUrls: Set<string>;
    wrapperOccurrenceCount: number;
    wrapperPageUrls: Set<string>;
    zones: Record<LinkZone, number>;
    occurrences: LinkOccurrence[];
};
type StatusRecord = {
    status: number;
    location: Location;
};
type FragmentRequest = {
    targetUrl: string;
    fragment: string;
    sourceUrl: string;
    rawHref: string;
    htmlSnippet?: string;
    zone: LinkZone;
};
type CanonicalReference = {
    sourceUrl: string;
    canonicalUrl: string;
};
type ExternalLinkRecord = {
    targetUrl: string;
    sources: Set<string>;
    rawHrefs: Set<string>;
    htmlSnippets: Set<string>;
    zones: Set<LinkZone>;
};
export default class LinkIssues extends BaseJob {
    name: string;
    configRequired: boolean;
    console: OutputHelper;
    issues: LinkIssue[];
    issueOccurrences: Map<string, LinkOccurrenceSummary>;
    statusByUrl: Map<string, StatusRecord>;
    redirectSources: Map<string, Location>;
    canonicalReferences: CanonicalReference[];
    nonCanonicalTargets: Set<string>;
    processedPageUrls: Set<string>;
    pageAnchors: Map<string, Set<string>>;
    fragmentRequests: FragmentRequest[];
    externalLinks: Map<string, ExternalLinkRecord>;
    assetLinks: Map<string, AssetRecord>;
    scannedAssetBodies: Set<string>;
    scannedPageCount: number;
    baseUrl: string;
    baseProtocol: string;
    baseHostname: string;
    allowedNonCanonicalLinks: string[];
    ignoredIssuePatterns: IgnoredIssuePattern[];
    undesirablePathCharacterPattern: RegExp;
    emailReportTriggerLevels: LinkIssueSeverity[] | null;
    includeNotices: boolean;
    includeExternal: boolean;
    includeAssets: boolean;
    promptOutput: boolean;
    constructor(handle: string, command: JobCommandParser, profiler: Profiler, runtime: ArachnodexRuntime);
    loadConfig(): void;
    shouldSendEmailReport(): boolean;
    getReportTitle(): string;
    getReportMessage(): string;
    getReportData(): ReportData;
    getReportHtml(): string;
    onHeadersReceived(_response: AxiosResponse | null, _location: Location): void;
    onPageReceived(_response: AxiosResponse | null, _pageData: PageData): void;
    onEnd(): Promise<void>;
    private addIssue;
    private getIssueKey;
    private shouldSuppressIssue;
    private matchesIgnoredIssuePattern;
    private getIgnoredIssueUrlCandidates;
    private isFilteredInternalUrl;
    private getReportKey;
    private reportIssues;
    private getPrintableIssues;
    private getIssueSeverityCounts;
    private getEmailReportSections;
    private getEmailEntryDetailLines;
    private getEntrySourceLines;
    private renderEmailReportSection;
    private renderEmailReportGroup;
    private renderEmailReportSubsection;
    private renderEmailReportEntry;
    private renderEmailWrapperMeta;
    private renderEmailSources;
    private escapeHtml;
    private linkifyHtml;
    private reportPromptIssues;
    private getPromptSections;
    private getPromptSectionKey;
    private getHighestPromptSeverity;
    private buildPromptText;
    private getPromptIssueTypeLabels;
    private getPromptSectionSeverityLabel;
    private getPromptSectionSeverities;
    private hasMultiplePromptIssueTypes;
    private hasMultiplePromptSeverities;
    private getPromptSectionGuidance;
    private getPromptGuidanceForIssue;
    private getEntryWrapperMeta;
    private shouldUseTargetUrlWrapperFallback;
    private getPromptSectionNote;
    private formatPromptEntryTitle;
    private getPromptEntryDetails;
    private getPromptWrapperDetails;
    private getSubheadingNotes;
    private getSubheadingKey;
    private reportHeading;
    private reportLine;
    private getReportEntries;
    private getIssueOccurrenceDetails;
    private getGroupSort;
    private getIssueSubheading;
    private isStatusIssue;
    private humanizeCode;
    private shouldShowSubheadingNote;
    private isAssetIssue;
    private isCanonicalIssue;
    private getCanonicalDetailLines;
    private formatIssue;
    private reportIssueDetails;
    private reportIssueSources;
    private auditParseWarnings;
    private issueFromParseWarning;
    private auditPageLinks;
    private collectPageAssets;
    private addAssetFromElement;
    private getLinkAssetKind;
    private addAssetReference;
    private addAssetContextIssue;
    private auditIframeSecurity;
    private auditAssetLinks;
    private auditAssetLinkWithTimeout;
    private auditAssetLink;
    private assetGetShowsReachableOrProtected;
    private shouldUseAssetGetFallback;
    private addAssetIssue;
    private addAssetBotProtectionNotice;
    private getAssetRequestConfig;
    private scanAssetBodyIfNeeded;
    private shouldScanAssetBody;
    private isCssAsset;
    private isJsAsset;
    private getContentType;
    private collectCssAssetReferences;
    private collectJsAssetReferences;
    private collectSourceMapReferences;
    private isConservativeJsAssetReference;
    private isStandaloneJsStringLiteral;
    private isRelativeJsModuleSpecifier;
    private parseSrcset;
    private isAssetMetaName;
    private isInsecureAssetReference;
    private getReachableHttpsUpgradeUrlByHead;
    private getElementLabel;
    private getElementSnippet;
    private getTextSnippet;
    private truncateText;
    private classifyAssetZone;
    private compileUndesirablePathCharacterPattern;
    private compileIgnoredIssuePatterns;
    private compileStringSelector;
    private compileSeveritySelector;
    private normalizeEmailReportTriggerLevels;
    private getDecodedUrlPath;
    private getDecodedUrlPathFromUrl;
    private addPageLinkIssue;
    private isBlankTargetMissingRel;
    private isInsecureInternalLink;
    private hasControlCharacters;
    private auditFragment;
    private auditDeferredFragments;
    private trackExternalLink;
    private auditExternalLinks;
    private auditExternalLinkWithTimeout;
    private auditExternalLink;
    private addExternalBotProtectionNotice;
    private externalGetShowsReachableOrProtected;
    private externalGetShowsReachable;
    private getExternalFallbackConfig;
    private isTemporaryDnsFailure;
    private getReachableHttpsUpgradeUrl;
    private getHttpsUpgradeUrl;
    private getExternalBotProtectionStatus;
    private getExternalOrHttpsUpgradeBotProtectionStatus;
    private externalGet;
    private externalHead;
    private getExternalRequestConfig;
    private runExternalRequest;
    private shouldRetryExternalRequest;
    private isAbortError;
    private isBotProtectionResponse;
    private getHeaderText;
    private auditCanonical;
    private isCanonicalQueryVariant;
    private shouldSkipOutgoingLinkAudit;
    private auditCanonicalTargets;
    private auditRedirects;
    private trackLinkOccurrences;
    private trackPageAnchors;
    private recordIssueOccurrence;
    private getLinkOccurrenceSummary;
    private getWrapperMeta;
    private getTopZone;
    private reportWrapperMeta;
    private getZoneSummary;
    private normalizeInternalUrl;
    private stripHash;
    private normalizeHostname;
}
