import type { PageData, ReportData } from "@arachnodex/core";
import { BaseJob, type ArachnodexRuntime, type JobCommandParser, type Profiler } from "@arachnodex/core";
export { default as CommandParser } from "./cmd.js";
export default class CspReport extends BaseJob {
    name: string;
    configRequired: boolean;
    private readonly console;
    private readonly sourceEntries;
    private readonly inlineFindings;
    private readonly nestedQueue;
    private readonly scannedNestedUrls;
    private readonly nestedFailures;
    private inlineFindingCount;
    private nestedFailureCount;
    private scannedPageCount;
    private ignoredPageCount;
    private scannedNestedCount;
    private outputFormat;
    private nested;
    private unsafeInline;
    private includeReportOnly;
    private includeEnforce;
    private reportUri;
    private reportTo;
    private promptOutput;
    private ignorePatterns;
    private additionalSources;
    private ignoreSources;
    private staticDirectives;
    private baseUrl;
    private baseOrigin;
    private baseProtocol;
    private baseHostname;
    constructor(handle: string, command: JobCommandParser, profiler: Profiler, runtime: ArachnodexRuntime);
    loadConfig(): void;
    onPageReceived(_response: unknown, pageData: PageData): void;
    onEnd(): Promise<void>;
    getReportTitle(): string;
    getReportMessage(): string;
    getReportData(): ReportData;
    getReportHtml(): string;
    private normalizeOutputFormat;
    private collectBaseUri;
    private isCspControlledScript;
    private collectScripts;
    private collectStyles;
    private collectImages;
    private collectMedia;
    private collectEmbeds;
    private collectForms;
    private collectInlineEventHandlers;
    private collectElementAttr;
    private collectSrcset;
    private getDocumentBaseUrl;
    private addElementReference;
    private addReference;
    private addSource;
    private addInlineFinding;
    private normalizeSource;
    private getSourceRiskReasons;
    private collectCssReferences;
    private collectJsReferences;
    private collectJsCallReferences;
    private collectJsImportReferences;
    private collectJsAssetLiteralReferences;
    private getDirectiveForAssetUrl;
    private scanNestedAssets;
    private getNextNestedUrl;
    private scanNestedAsset;
    private getNestedRequestConfig;
    private queueNestedScanIfNeeded;
    private buildPolicy;
    private getPolicyDirectives;
    private addPolicySource;
    private getHeaderDirectives;
    private renderDirectives;
    private renderHeaderDirective;
    private reportFindings;
    private getWarningGroups;
    private hasLikelyEnforceBreakage;
    private getHeaderUseTitle;
    private getHeaderUseExplanation;
    private renderWarningGroupHtml;
    private reportWarningGroup;
    private reportPromptWarnings;
    private buildPromptText;
    private getInlineWarningItems;
    private getInlineFindingCount;
    private getSampleSourceUrls;
    private getRiskyEntries;
    private hasInlineKind;
    private isIgnoredSource;
    private matchesIgnorePattern;
    private compilePatterns;
    private safeDecode;
    private getSortedDirectiveNames;
    private getSortedSources;
    private getSourceSortRank;
    private isConservativeJsReference;
    private shouldSkipInactiveHttpProtocolBranch;
    private isStandaloneJsStringLiteral;
    private isRelativeJsModuleSpecifier;
    private isNestedScannable;
    private getExtension;
    private getFilename;
    private isSameOrigin;
    private isSameSite;
    private normalizeHostname;
    private parseSrcset;
    private classifyZone;
    private escapeConfigValue;
    private escapeHtml;
    private getElementSnippet;
    private getTextSnippet;
}
