import type { PageData, ReportData } from "@arachnodex/core";
import { BaseJob, type ArachnodexRuntime, type JobCommandParser, type Profiler } from "@arachnodex/core";
export { default as CommandParser } from "./cmd.js";
export default class NfaReport extends BaseJob {
    name: string;
    configRequired: boolean;
    private readonly console;
    private readonly findings;
    private readonly nestedQueue;
    private readonly scannedNestedUrls;
    private readonly failedNestedUrls;
    private limitMail;
    private verbose;
    private nested;
    private viteRollupFingerprintCompatibility;
    private promptOutput;
    private scannedPageCount;
    private scannedNestedCount;
    private fingerprintPattern;
    private fingerprintSeparatorPattern;
    private ignorePatterns;
    private qsProps;
    private assetExtensions;
    private mediaExtensions;
    private documentExtensions;
    private baseUrl;
    private baseHostname;
    constructor(handle: string, command: JobCommandParser, profiler: Profiler, runtime: ArachnodexRuntime);
    loadConfig(): void;
    onPageReceived(_response: unknown, pageData: PageData): void;
    onEnd(): Promise<void>;
    getReportTitle(): string;
    getReportMessage(): string;
    getReportData(): ReportData;
    getReportHtml(): string;
    shouldSendEmailReport(): boolean;
    private collectLinkElements;
    private collectElementAttr;
    private collectSrcset;
    private collectMetaAssets;
    private collectAnchorAssets;
    private collectInlineStyles;
    private collectStyleTags;
    private addElementReference;
    private addReference;
    private queueNestedScanIfNeeded;
    private scanNestedAssets;
    private getNextNestedUrl;
    private scanNestedAsset;
    private getNestedRequestConfig;
    private collectCssReferences;
    private collectJsReferences;
    private collectSourceMapReferences;
    private isConservativeJsAssetReference;
    private isStandaloneJsStringLiteral;
    private isRelativeJsModuleSpecifier;
    private isFingerprinted;
    private getFingerprintHashSegment;
    private hasDefaultBundlerFingerprint;
    private isHashLikeSegment;
    private hasAcceptedQueryFingerprint;
    private matchesIgnorePattern;
    private getAssetGroup;
    private getExtension;
    private getFilename;
    private isNestedScannable;
    private isSameSite;
    private isWebReference;
    private parseSrcset;
    private isAssetMetaName;
    private classifyZone;
    private compileFingerprintPattern;
    private compileFingerprintSeparatorPattern;
    private compilePatterns;
    private compileQsProps;
    private normalizeExtensions;
    private normalizeHostname;
    private safeDecode;
    private reportFindings;
    private reportPromptFindings;
    private buildPromptText;
    private getPromptEntryDetails;
    private getSortedFindings;
    private getOccurrenceCount;
    private groupLabel;
    private renderEmailEntry;
    private getElementSnippet;
    private getTextSnippet;
    private truncateText;
    private escapeHtml;
    private linkifyHtml;
}
