import type { Location, CrawlerError, CrawlerStats, PageAuditOutcome } from "./definitions.ts";
import { ArachnodexThread } from "./arachnodexThread.js";
import { OutputHelper } from "./services/outputHelper.js";
import { JobManager } from "./services/jobManager.js";
import type { MainCommandParser } from "./command/mainCommandParser.js";
import { Profiler } from "./services/profiler.js";
import { ArachnodexRuntime } from "./runtime.js";
import type { AxiosResponse } from "axios";
export declare class Arachnodex {
    private readonly runtime;
    jobs: JobManager;
    profiler: Profiler;
    fatalShutdownStarted: boolean;
    fatalShutdownPromise?: Promise<void>;
    errors: CrawlerError[];
    threadCount: number;
    pending: Location[];
    pendingDelayed: Location[];
    visited: Record<string, Location>;
    canonicalAliases: Record<string, string>;
    pendingUrlHashes: string[];
    pendingUrls: string[];
    crawlStarted: boolean;
    maxThreadsCreated: boolean;
    maxThreads: number;
    verbosityLevel: number;
    muteResponseStatus: boolean;
    baseUrl: string;
    console: OutputHelper;
    stats: CrawlerStats;
    constructor(command: MainCommandParser, runtime?: ArachnodexRuntime);
    private normalizeHostname;
    private emitConfigError;
    start(): Promise<number>;
    shutdown(): Promise<void>;
    sendTestReportEmail(): Promise<void>;
    private getTestReportStats;
    locationHash(loc: Location): string;
    addNewLocation(location: Location): Promise<false | undefined>;
    isFetchReady(locationUrl: string): boolean;
    removePendingHash(location: Location): void;
    locationLogVisitedEvent(locationUrl: string, statusCode: number): void;
    retryLocationEvent(location: Location): Promise<void>;
    updateVisitedLocation(location: Location): void;
    locationsAddedEvent(): Promise<void>;
    workerInFlight(): boolean;
    threadReadyEvent(thread: ArachnodexThread): Promise<void>;
    beforeRequestEvent(location: Location): void;
    headersReceivedEvent(response: AxiosResponse | null, location: Location): void;
    pageReceivedEvent(response: AxiosResponse | null, location: Location, auditOutcome?: PageAuditOutcome): void;
    private registerCanonicalAlias;
    private isCanonicalAliasAlreadyProcessed;
    private getPreparedLocationUrl;
    private createParseWarning;
    private createPageLink;
    private getAnchorHtmlSnippet;
    private getTrimmedAnchorRenderedContent;
    private trimUtf8Bytes;
    private isLocationInScope;
    private isFilteredInternalUrl;
    private isExternalUrl;
    private classifyLinkZone;
    errorEventHandler(e: Error, message?: string, location?: Location, suppressEmail?: boolean, fatal?: boolean): void;
    private finalizeFatalShutdown;
    private waitForActiveThreadsToSettle;
    private sendFatalErrorReport;
}
